spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
